### ISSUE TITLE
Page problem

### ISSUE THREAD

**Issue by iDavid86920** [MrAnonymusz/AdvancedReporterWebGui#1]
Hi. I have a problem with the page. I already have everything configured, MySQL activated and connected to the plugin and working correctly. The problem I think arises on the page and is when loading the reports. They leave the following errors on my pc, phone and other equipment.

![image](https://user-images.githubusercontent.com/36801628/38846829-194e671e-41c4-11e8-8faa-21cb6e040594.png)
![image](https://user-images.githubusercontent.com/36801628/38846833-1cc27a98-41c4-11e8-8fb9-ab5eba29bc0f.png)
![image](https://user-images.githubusercontent.com/36801628/38846836-1fa083a4-41c4-11e8-92cf-03e6789aa81a.png)

From what I see it is the error of the page (possibly mine) but I do not know what I did wrong. Thank you very much, the truth is a plugin that I see that you put an ear and is very good also very cheap for what really is worth. Thank you.

**Comment by MrAnonymusz** [comment]
@iDavid86920 Sorry for the late answer, make sure the table_name setting is the same with the table name (They must be identical one can't be with lowercases and the other with uppercases or viceversa). Or try to read [this article](https://www.lifewire.com/500-internal-server-error-explained-2622938).
