### ISSUE TITLE
"you will be redirected in a few seconds" is INSANELY too long.

### ISSUE THREAD

**Issue by FrozenBeard** [MrAnonymusz/AdvancedReporterWebGui#3]
Its so confusing, you dont know whats happening, if the page needs to redirect, do it instantly. The fact you have to wait for whatever its doing just dousnt make sense. Its something insane like 5 seconds? it needs to be instant.

**Comment by MrAnonymusz** [comment]
@FrozenBeard I will decrease the timer but I won't romve it.
