### ISSUE TITLE
Support/Move to BanManager Reports.

### ISSUE THREAD

**Issue by FrozenBeard** [MrAnonymusz/AdvancedReporterWebGui#4]
BanManager is a mature fully feature rich Punishments system, there already exists a web UI for displaying player punishments but there isn't a way to manage their Reports system, its on par with AdvancedReporter, since its such a mature plugin migrating the web UI or adding support would be a good move to a wider community, they work in a similar way too.

https://dev.bukkit.org/projects/ban-management
https://github.com/BanManagement/BanManager

**Comment by MrAnonymusz** [comment]
@FrozenBeard I sent a message to the team.
