### ISSUE TITLE
Support mantisbt.org

### ISSUE THREAD

**Issue by FrozenBeard** [MrAnonymusz/AdvancedReporterWebGui#5]
Instead of trying to recreate the wheel, why not support a project that's been around for 10 year's. A reporter is just a ticket manager, use something that exists. https://www.mantisbt.org I use this as it's tried and tested, it's got an api, it's hell more powerful. An insnae amount of features, security and third-party apps.

**Comment by MrAnonymusz** [comment]
@FrozenBeard Well I don't want ot move my support to any other frameworks (projects) and I'm fine with this project how it is and with his features. It's good for this plugin and I think it has the basic things for a report manager.
